#!/usr/bin/env python3

import pytest
from pyspark.sql.window import Window
from pyspark.sql import functions as FN
from .programaestudiante import *

def test_total_productos(spark_session):
    sc=spark_session.sparkContext
    # strings en formato JSON de prueba
    json1 = [{"numero_caja": 1, "compras": [[{"nombre": "naranja", "precio_unitario": 350, "cantidad": 11}, {"nombre": "galletas", "precio_unitario": 800, "cantidad": 8}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 8}], [{"nombre": "naranja", "precio_unitario": 350, "cantidad": 11}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 8}], [{"nombre": "naranja", "precio_unitario": 350, "cantidad": 11}, {"nombre": "jugo", "precio_unitario": 950, "cantidad": 8}, {"nombre": "sandia", "precio_unitario": 1500, "cantidad": 7}], [{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 1}], [{"nombre": "sandia", "precio_unitario": 1500, "cantidad": 7}], [{"nombre": "sandia", "precio_unitario": 1500, "cantidad": 7}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 1}], [{"nombre": "sandia", "precio_unitario": 1500, "cantidad": 7}], [{"nombre": "sandia", "precio_unitario": 1500, "cantidad": 7}]]}]
    json2 = [{"numero_caja": 2, "compras": [[{"nombre": "agua", "precio_unitario": 650, "cantidad": 11}, {"nombre": "agua", "precio_unitario": 650, "cantidad": 11}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 3}, {"nombre": "agua", "precio_unitario": 650, "cantidad": 11}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 3}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 3}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 13}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 3}, {"nombre": "jugo", "precio_unitario": 950, "cantidad": 3}], [{"nombre": "manzana", "precio_unitario": 400, "cantidad": 12}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 13}], [{"nombre": "naranja", "precio_unitario": 350, "cantidad": 8}, {"nombre": "sandia", "precio_unitario": 1500, "cantidad": 6}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 3}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 13}, {"nombre": "agua", "precio_unitario": 650, "cantidad": 11}], [{"nombre": "sandia", "precio_unitario": 1500, "cantidad": 6}, {"nombre": "galletas", "precio_unitario": 800, "cantidad": 13}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 3}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 8}, {"nombre": "galletas", "precio_unitario": 800, "cantidad": 13}]]}]
    json3 = [{"numero_caja": 3, "compras": [[{"nombre": "sandia", "precio_unitario": 1500, "cantidad": 3}], [{"nombre": "manzana", "precio_unitario": 400, "cantidad": 13}, {"nombre": "galletas", "precio_unitario": 800, "cantidad": 12}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 1}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 5}, {"nombre": "manzana", "precio_unitario": 400, "cantidad": 13}, {"nombre": "manzana", "precio_unitario": 400, "cantidad": 13}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 5}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 9}], [{"nombre": "manzana", "precio_unitario": 400, "cantidad": 13}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 1}, {"nombre": "sandia", "precio_unitario": 1500, "cantidad": 3}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 8}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 9}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 12}, {"nombre": "jugo", "precio_unitario": 950, "cantidad": 5}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 8}], [{"nombre": "manzana", "precio_unitario": 400, "cantidad": 13}], [{"nombre": "sandia", "precio_unitario": 1500, "cantidad": 3}, {"nombre": "galletas", "precio_unitario": 800, "cantidad": 12}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 8}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 5}]]}]
    json4 = [{"numero_caja": 4, "compras": [[{"nombre": "jugo", "precio_unitario": 950, "cantidad": 11}, {"nombre": "sandia", "precio_unitario": 1500, "cantidad": 3}], [{"nombre": "manzana", "precio_unitario": 400, "cantidad": 14}, {"nombre": "agua", "precio_unitario": 650, "cantidad": 7}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 3}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 11}, {"nombre": "galletas", "precio_unitario": 800, "cantidad": 7}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 11}], [{"nombre": "naranja", "precio_unitario": 350, "cantidad": 8}], [{"nombre": "manzana", "precio_unitario": 400, "cantidad": 14}, {"nombre": "jugo", "precio_unitario": 950, "cantidad": 11}, {"nombre": "jugo", "precio_unitario": 950, "cantidad": 11}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 5}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 5}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 5}, {"nombre": "jugo", "precio_unitario": 950, "cantidad": 11}], [{"nombre": "sandia", "precio_unitario": 1500, "cantidad": 3}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 5}, {"nombre": "manzana", "precio_unitario": 400, "cantidad": 14}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 7}, {"nombre": "agua", "precio_unitario": 650, "cantidad": 7}]]}]
    json5 = [{"numero_caja": 5, "compras": [[{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 4}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 6}], [{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 9}], [{"nombre": "manzana", "precio_unitario": 400, "cantidad": 4}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 9}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 4}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 12}, {"nombre": "sandia", "precio_unitario": 1500, "cantidad": 1}], [{"nombre": "naranja", "precio_unitario": 350, "cantidad": 6}, {"nombre": "jugo", "precio_unitario": 950, "cantidad": 12}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 6}], [{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 9}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 6}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 12}], [{"nombre": "sandia", "precio_unitario": 1500, "cantidad": 1}, {"nombre": "galletas", "precio_unitario": 800, "cantidad": 5}, {"nombre": "galletas", "precio_unitario": 800, "cantidad": 5}], [{"nombre": "naranja", "precio_unitario": 350, "cantidad": 6}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 9}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 4}, {"nombre": "jugo", "precio_unitario": 950, "cantidad": 12}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 9}]]}]
    json6 = [{"numero_caja": 6, "compras": [[{"nombre": "manzana", "precio_unitario": 400, "cantidad": 3}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 5}], [{"nombre": "agua", "precio_unitario": 650, "cantidad": 3}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 10}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 3}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 10}], [{"nombre": "agua", "precio_unitario": 650, "cantidad": 3}, {"nombre": "agua", "precio_unitario": 650, "cantidad": 3}], [{"nombre": "naranja", "precio_unitario": 350, "cantidad": 10}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 8}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 8}, {"nombre": "jugo", "precio_unitario": 950, "cantidad": 3}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 10}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 13}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 8}], [{"nombre": "agua", "precio_unitario": 650, "cantidad": 3}], [{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 5}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 5}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 10}]]}]
    json7 = [{"numero_caja": 7, "compras": [[{"nombre": "jugo", "precio_unitario": 950, "cantidad": 1}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 12}, {"nombre": "sandia", "precio_unitario": 1500, "cantidad": 2}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 4}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 12}, {"nombre": "galletas", "precio_unitario": 800, "cantidad": 4}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 13}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 13}, {"nombre": "manzana", "precio_unitario": 400, "cantidad": 4}, {"nombre": "jugo", "precio_unitario": 950, "cantidad": 1}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 13}, {"nombre": "agua", "precio_unitario": 650, "cantidad": 12}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 4}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 13}, {"nombre": "galletas", "precio_unitario": 800, "cantidad": 4}], [{"nombre": "sandia", "precio_unitario": 1500, "cantidad": 2}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 12}, {"nombre": "manzana", "precio_unitario": 400, "cantidad": 4}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 4}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 12}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 13}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 4}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 4}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 12}]]}]
    json8 = [{"numero_caja": 8, "compras": [[{"nombre": "jugo", "precio_unitario": 950, "cantidad": 1}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 1}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 1}], [{"nombre": "naranja", "precio_unitario": 350, "cantidad": 1}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 1}, {"nombre": "agua", "precio_unitario": 650, "cantidad": 10}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 3}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 1}, {"nombre": "manzana", "precio_unitario": 400, "cantidad": 13}, {"nombre": "agua", "precio_unitario": 650, "cantidad": 10}], [{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 7}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 5}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 7}], [{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 7}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 3}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 7}], [{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 7}, {"nombre": "sandia", "precio_unitario": 1500, "cantidad": 14}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 3}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 5}]]}]
    json9 = [{"numero_caja": 9, "compras": [[{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 2}, {"nombre": "manzana", "precio_unitario": 400, "cantidad": 13}], [{"nombre": "manzana", "precio_unitario": 400, "cantidad": 13}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 13}, {"nombre": "sandia", "precio_unitario": 1500, "cantidad": 13}], [{"nombre": "agua", "precio_unitario": 650, "cantidad": 9}, {"nombre": "jugo", "precio_unitario": 950, "cantidad": 10}], [{"nombre": "naranja", "precio_unitario": 350, "cantidad": 11}, {"nombre": "sandia", "precio_unitario": 1500, "cantidad": 13}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 13}], [{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 2}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 4}], [{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 2}, {"nombre": "galletas", "precio_unitario": 800, "cantidad": 13}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 4}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 13}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 11}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 2}]]}]
    json10 = [{"numero_caja": 10, "compras": [[{"nombre": "galletas", "precio_unitario": 800, "cantidad": 4}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 4}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 5}], [{"nombre": "naranja", "precio_unitario": 350, "cantidad": 4}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 5}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 5}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 4}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 4}, {"nombre": "manzana", "precio_unitario": 400, "cantidad": 6}], [{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 5}, {"nombre": "agua", "precio_unitario": 650, "cantidad": 7}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 4}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 1}], [{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 5}, {"nombre": "sandia", "precio_unitario": 1500, "cantidad": 11}, {"nombre": "sandia", "precio_unitario": 1500, "cantidad": 11}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 1}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 1}, {"nombre": "manzana", "precio_unitario": 400, "cantidad": 6}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 4}]]}]

    jsonString = json1 + json2 + json3 + json4 + json5 + json6 + json7 + json8 + json9 + json10     
    print("jsonString",jsonString)
    dataframe =sc.parallelize(jsonString)
    testDF = readFiles(dataframe)   # Creción del Dataframe de Prueba
    SubtotalsDF = testDF.withColumn("SubTotal", \
                        testDF.cantidad * testDF.precio_unitario)

    #Output de la función programada
    actual_ds = fn_total_productos(SubtotalsDF)    
    actual_ds.show()
    actual_ds.printSchema()

    #Output esperado
    #nombre|CantidadTotal
    expected_ds = spark_session.createDataFrame(
        [
            ("jugo" , 194), 
            ("sandia" , 130), 
            ("manzana" , 185), 
            ("galletas" , 239), 
            ("agua" , 118), 
            ("uvas" , 159), 
            ("cafe" , 176), 
            ("naranja" , 236) 
            
        ], 
        [   'nombre', 'CantidadTotal'])  
    expected_ds.show()                                                                                     
    

    assert expected_ds.collect() == actual_ds.collect()


def test_total_cajas(spark_session):
    sc=spark_session.sparkContext
    # strings en formato JSON de prueba
    json1 = [{"numero_caja": 1, "compras": [[{"nombre": "naranja", "precio_unitario": 350, "cantidad": 11}, {"nombre": "galletas", "precio_unitario": 800, "cantidad": 8}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 8}], [{"nombre": "naranja", "precio_unitario": 350, "cantidad": 11}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 8}], [{"nombre": "naranja", "precio_unitario": 350, "cantidad": 11}, {"nombre": "jugo", "precio_unitario": 950, "cantidad": 8}, {"nombre": "sandia", "precio_unitario": 1500, "cantidad": 7}], [{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 1}], [{"nombre": "sandia", "precio_unitario": 1500, "cantidad": 7}], [{"nombre": "sandia", "precio_unitario": 1500, "cantidad": 7}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 1}], [{"nombre": "sandia", "precio_unitario": 1500, "cantidad": 7}], [{"nombre": "sandia", "precio_unitario": 1500, "cantidad": 7}]]}]
    json2 = [{"numero_caja": 2, "compras": [[{"nombre": "agua", "precio_unitario": 650, "cantidad": 11}, {"nombre": "agua", "precio_unitario": 650, "cantidad": 11}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 3}, {"nombre": "agua", "precio_unitario": 650, "cantidad": 11}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 3}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 3}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 13}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 3}, {"nombre": "jugo", "precio_unitario": 950, "cantidad": 3}], [{"nombre": "manzana", "precio_unitario": 400, "cantidad": 12}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 13}], [{"nombre": "naranja", "precio_unitario": 350, "cantidad": 8}, {"nombre": "sandia", "precio_unitario": 1500, "cantidad": 6}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 3}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 13}, {"nombre": "agua", "precio_unitario": 650, "cantidad": 11}], [{"nombre": "sandia", "precio_unitario": 1500, "cantidad": 6}, {"nombre": "galletas", "precio_unitario": 800, "cantidad": 13}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 3}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 8}, {"nombre": "galletas", "precio_unitario": 800, "cantidad": 13}]]}]
    json3 = [{"numero_caja": 3, "compras": [[{"nombre": "sandia", "precio_unitario": 1500, "cantidad": 3}], [{"nombre": "manzana", "precio_unitario": 400, "cantidad": 13}, {"nombre": "galletas", "precio_unitario": 800, "cantidad": 12}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 1}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 5}, {"nombre": "manzana", "precio_unitario": 400, "cantidad": 13}, {"nombre": "manzana", "precio_unitario": 400, "cantidad": 13}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 5}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 9}], [{"nombre": "manzana", "precio_unitario": 400, "cantidad": 13}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 1}, {"nombre": "sandia", "precio_unitario": 1500, "cantidad": 3}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 8}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 9}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 12}, {"nombre": "jugo", "precio_unitario": 950, "cantidad": 5}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 8}], [{"nombre": "manzana", "precio_unitario": 400, "cantidad": 13}], [{"nombre": "sandia", "precio_unitario": 1500, "cantidad": 3}, {"nombre": "galletas", "precio_unitario": 800, "cantidad": 12}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 8}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 5}]]}]
    json4 = [{"numero_caja": 4, "compras": [[{"nombre": "jugo", "precio_unitario": 950, "cantidad": 11}, {"nombre": "sandia", "precio_unitario": 1500, "cantidad": 3}], [{"nombre": "manzana", "precio_unitario": 400, "cantidad": 14}, {"nombre": "agua", "precio_unitario": 650, "cantidad": 7}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 3}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 11}, {"nombre": "galletas", "precio_unitario": 800, "cantidad": 7}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 11}], [{"nombre": "naranja", "precio_unitario": 350, "cantidad": 8}], [{"nombre": "manzana", "precio_unitario": 400, "cantidad": 14}, {"nombre": "jugo", "precio_unitario": 950, "cantidad": 11}, {"nombre": "jugo", "precio_unitario": 950, "cantidad": 11}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 5}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 5}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 5}, {"nombre": "jugo", "precio_unitario": 950, "cantidad": 11}], [{"nombre": "sandia", "precio_unitario": 1500, "cantidad": 3}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 5}, {"nombre": "manzana", "precio_unitario": 400, "cantidad": 14}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 7}, {"nombre": "agua", "precio_unitario": 650, "cantidad": 7}]]}]
    json5 = [{"numero_caja": 5, "compras": [[{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 4}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 6}], [{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 9}], [{"nombre": "manzana", "precio_unitario": 400, "cantidad": 4}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 9}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 4}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 12}, {"nombre": "sandia", "precio_unitario": 1500, "cantidad": 1}], [{"nombre": "naranja", "precio_unitario": 350, "cantidad": 6}, {"nombre": "jugo", "precio_unitario": 950, "cantidad": 12}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 6}], [{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 9}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 6}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 12}], [{"nombre": "sandia", "precio_unitario": 1500, "cantidad": 1}, {"nombre": "galletas", "precio_unitario": 800, "cantidad": 5}, {"nombre": "galletas", "precio_unitario": 800, "cantidad": 5}], [{"nombre": "naranja", "precio_unitario": 350, "cantidad": 6}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 9}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 4}, {"nombre": "jugo", "precio_unitario": 950, "cantidad": 12}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 9}]]}]
    json6 = [{"numero_caja": 6, "compras": [[{"nombre": "manzana", "precio_unitario": 400, "cantidad": 3}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 5}], [{"nombre": "agua", "precio_unitario": 650, "cantidad": 3}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 10}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 3}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 10}], [{"nombre": "agua", "precio_unitario": 650, "cantidad": 3}, {"nombre": "agua", "precio_unitario": 650, "cantidad": 3}], [{"nombre": "naranja", "precio_unitario": 350, "cantidad": 10}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 8}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 8}, {"nombre": "jugo", "precio_unitario": 950, "cantidad": 3}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 10}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 13}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 8}], [{"nombre": "agua", "precio_unitario": 650, "cantidad": 3}], [{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 5}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 5}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 10}]]}]
    json7 = [{"numero_caja": 7, "compras": [[{"nombre": "jugo", "precio_unitario": 950, "cantidad": 1}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 12}, {"nombre": "sandia", "precio_unitario": 1500, "cantidad": 2}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 4}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 12}, {"nombre": "galletas", "precio_unitario": 800, "cantidad": 4}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 13}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 13}, {"nombre": "manzana", "precio_unitario": 400, "cantidad": 4}, {"nombre": "jugo", "precio_unitario": 950, "cantidad": 1}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 13}, {"nombre": "agua", "precio_unitario": 650, "cantidad": 12}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 4}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 13}, {"nombre": "galletas", "precio_unitario": 800, "cantidad": 4}], [{"nombre": "sandia", "precio_unitario": 1500, "cantidad": 2}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 12}, {"nombre": "manzana", "precio_unitario": 400, "cantidad": 4}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 4}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 12}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 13}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 4}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 4}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 12}]]}]
    json8 = [{"numero_caja": 8, "compras": [[{"nombre": "jugo", "precio_unitario": 950, "cantidad": 1}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 1}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 1}], [{"nombre": "naranja", "precio_unitario": 350, "cantidad": 1}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 1}, {"nombre": "agua", "precio_unitario": 650, "cantidad": 10}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 3}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 1}, {"nombre": "manzana", "precio_unitario": 400, "cantidad": 13}, {"nombre": "agua", "precio_unitario": 650, "cantidad": 10}], [{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 7}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 5}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 7}], [{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 7}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 3}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 7}], [{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 7}, {"nombre": "sandia", "precio_unitario": 1500, "cantidad": 14}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 3}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 5}]]}]
    json9 = [{"numero_caja": 9, "compras": [[{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 2}, {"nombre": "manzana", "precio_unitario": 400, "cantidad": 13}], [{"nombre": "manzana", "precio_unitario": 400, "cantidad": 13}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 13}, {"nombre": "sandia", "precio_unitario": 1500, "cantidad": 13}], [{"nombre": "agua", "precio_unitario": 650, "cantidad": 9}, {"nombre": "jugo", "precio_unitario": 950, "cantidad": 10}], [{"nombre": "naranja", "precio_unitario": 350, "cantidad": 11}, {"nombre": "sandia", "precio_unitario": 1500, "cantidad": 13}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 13}], [{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 2}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 4}], [{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 2}, {"nombre": "galletas", "precio_unitario": 800, "cantidad": 13}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 4}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 13}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 11}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 2}]]}]
    json10 = [{"numero_caja": 10, "compras": [[{"nombre": "galletas", "precio_unitario": 800, "cantidad": 4}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 4}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 5}], [{"nombre": "naranja", "precio_unitario": 350, "cantidad": 4}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 5}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 5}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 4}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 4}, {"nombre": "manzana", "precio_unitario": 400, "cantidad": 6}], [{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 5}, {"nombre": "agua", "precio_unitario": 650, "cantidad": 7}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 4}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 1}], [{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 5}, {"nombre": "sandia", "precio_unitario": 1500, "cantidad": 11}, {"nombre": "sandia", "precio_unitario": 1500, "cantidad": 11}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 1}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 1}, {"nombre": "manzana", "precio_unitario": 400, "cantidad": 6}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 4}]]}]

    jsonString = json1 + json2 + json3 + json4 + json5 + json6 + json7 + json8 + json9 + json10     
    print("jsonString",jsonString)
    dataframe =sc.parallelize(jsonString)
    testDF = readFiles(dataframe)   # Creción del Dataframe de Prueba
    SubtotalsDF = testDF.withColumn("SubTotal", \
                        testDF.cantidad * testDF.precio_unitario)

    #Output de la función programada
    actual_ds = fn_total_por_caja(SubtotalsDF)    
    actual_ds.show()
    actual_ds.printSchema()

    #Output esperado
    #nombre|CantidadTotal
    expected_ds = spark_session.createDataFrame(
        [
            (7  , 150050 ), 
            (6  , 93000), 
            (9  , 134450) , 
            (5  , 138900) , 
            (1  , 95650) , 
            (10 , 92950) , 
            (3  , 142000) , 
            (8  , 105250) , 
            (2  , 137750) , 
            (4  , 142200)             
        ], 
        [   'numero_caja', 'Total_Dinero_Vendido'])  
    expected_ds.show()                                                                                     
    

    assert expected_ds.collect() == actual_ds.collect()



def test_metricas(spark_session):
    sc=spark_session.sparkContext
    # strings en formato JSON de prueba
    json1 = [{"numero_caja": 1, "compras": [[{"nombre": "naranja", "precio_unitario": 350, "cantidad": 11}, {"nombre": "galletas", "precio_unitario": 800, "cantidad": 8}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 8}], [{"nombre": "naranja", "precio_unitario": 350, "cantidad": 11}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 8}], [{"nombre": "naranja", "precio_unitario": 350, "cantidad": 11}, {"nombre": "jugo", "precio_unitario": 950, "cantidad": 8}, {"nombre": "sandia", "precio_unitario": 1500, "cantidad": 7}], [{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 1}], [{"nombre": "sandia", "precio_unitario": 1500, "cantidad": 7}], [{"nombre": "sandia", "precio_unitario": 1500, "cantidad": 7}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 1}], [{"nombre": "sandia", "precio_unitario": 1500, "cantidad": 7}], [{"nombre": "sandia", "precio_unitario": 1500, "cantidad": 7}]]}]
    json2 = [{"numero_caja": 2, "compras": [[{"nombre": "agua", "precio_unitario": 650, "cantidad": 11}, {"nombre": "agua", "precio_unitario": 650, "cantidad": 11}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 3}, {"nombre": "agua", "precio_unitario": 650, "cantidad": 11}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 3}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 3}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 13}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 3}, {"nombre": "jugo", "precio_unitario": 950, "cantidad": 3}], [{"nombre": "manzana", "precio_unitario": 400, "cantidad": 12}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 13}], [{"nombre": "naranja", "precio_unitario": 350, "cantidad": 8}, {"nombre": "sandia", "precio_unitario": 1500, "cantidad": 6}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 3}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 13}, {"nombre": "agua", "precio_unitario": 650, "cantidad": 11}], [{"nombre": "sandia", "precio_unitario": 1500, "cantidad": 6}, {"nombre": "galletas", "precio_unitario": 800, "cantidad": 13}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 3}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 8}, {"nombre": "galletas", "precio_unitario": 800, "cantidad": 13}]]}]
    json3 = [{"numero_caja": 3, "compras": [[{"nombre": "sandia", "precio_unitario": 1500, "cantidad": 3}], [{"nombre": "manzana", "precio_unitario": 400, "cantidad": 13}, {"nombre": "galletas", "precio_unitario": 800, "cantidad": 12}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 1}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 5}, {"nombre": "manzana", "precio_unitario": 400, "cantidad": 13}, {"nombre": "manzana", "precio_unitario": 400, "cantidad": 13}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 5}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 9}], [{"nombre": "manzana", "precio_unitario": 400, "cantidad": 13}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 1}, {"nombre": "sandia", "precio_unitario": 1500, "cantidad": 3}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 8}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 9}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 12}, {"nombre": "jugo", "precio_unitario": 950, "cantidad": 5}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 8}], [{"nombre": "manzana", "precio_unitario": 400, "cantidad": 13}], [{"nombre": "sandia", "precio_unitario": 1500, "cantidad": 3}, {"nombre": "galletas", "precio_unitario": 800, "cantidad": 12}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 8}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 5}]]}]
    json4 = [{"numero_caja": 4, "compras": [[{"nombre": "jugo", "precio_unitario": 950, "cantidad": 11}, {"nombre": "sandia", "precio_unitario": 1500, "cantidad": 3}], [{"nombre": "manzana", "precio_unitario": 400, "cantidad": 14}, {"nombre": "agua", "precio_unitario": 650, "cantidad": 7}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 3}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 11}, {"nombre": "galletas", "precio_unitario": 800, "cantidad": 7}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 11}], [{"nombre": "naranja", "precio_unitario": 350, "cantidad": 8}], [{"nombre": "manzana", "precio_unitario": 400, "cantidad": 14}, {"nombre": "jugo", "precio_unitario": 950, "cantidad": 11}, {"nombre": "jugo", "precio_unitario": 950, "cantidad": 11}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 5}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 5}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 5}, {"nombre": "jugo", "precio_unitario": 950, "cantidad": 11}], [{"nombre": "sandia", "precio_unitario": 1500, "cantidad": 3}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 5}, {"nombre": "manzana", "precio_unitario": 400, "cantidad": 14}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 7}, {"nombre": "agua", "precio_unitario": 650, "cantidad": 7}]]}]
    json5 = [{"numero_caja": 5, "compras": [[{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 4}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 6}], [{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 9}], [{"nombre": "manzana", "precio_unitario": 400, "cantidad": 4}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 9}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 4}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 12}, {"nombre": "sandia", "precio_unitario": 1500, "cantidad": 1}], [{"nombre": "naranja", "precio_unitario": 350, "cantidad": 6}, {"nombre": "jugo", "precio_unitario": 950, "cantidad": 12}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 6}], [{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 9}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 6}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 12}], [{"nombre": "sandia", "precio_unitario": 1500, "cantidad": 1}, {"nombre": "galletas", "precio_unitario": 800, "cantidad": 5}, {"nombre": "galletas", "precio_unitario": 800, "cantidad": 5}], [{"nombre": "naranja", "precio_unitario": 350, "cantidad": 6}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 9}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 4}, {"nombre": "jugo", "precio_unitario": 950, "cantidad": 12}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 9}]]}]
    json6 = [{"numero_caja": 6, "compras": [[{"nombre": "manzana", "precio_unitario": 400, "cantidad": 3}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 5}], [{"nombre": "agua", "precio_unitario": 650, "cantidad": 3}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 10}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 3}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 10}], [{"nombre": "agua", "precio_unitario": 650, "cantidad": 3}, {"nombre": "agua", "precio_unitario": 650, "cantidad": 3}], [{"nombre": "naranja", "precio_unitario": 350, "cantidad": 10}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 8}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 8}, {"nombre": "jugo", "precio_unitario": 950, "cantidad": 3}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 10}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 13}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 8}], [{"nombre": "agua", "precio_unitario": 650, "cantidad": 3}], [{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 5}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 5}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 10}]]}]
    json7 = [{"numero_caja": 7, "compras": [[{"nombre": "jugo", "precio_unitario": 950, "cantidad": 1}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 12}, {"nombre": "sandia", "precio_unitario": 1500, "cantidad": 2}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 4}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 12}, {"nombre": "galletas", "precio_unitario": 800, "cantidad": 4}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 13}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 13}, {"nombre": "manzana", "precio_unitario": 400, "cantidad": 4}, {"nombre": "jugo", "precio_unitario": 950, "cantidad": 1}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 13}, {"nombre": "agua", "precio_unitario": 650, "cantidad": 12}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 4}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 13}, {"nombre": "galletas", "precio_unitario": 800, "cantidad": 4}], [{"nombre": "sandia", "precio_unitario": 1500, "cantidad": 2}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 12}, {"nombre": "manzana", "precio_unitario": 400, "cantidad": 4}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 4}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 12}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 13}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 4}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 4}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 12}]]}]
    json8 = [{"numero_caja": 8, "compras": [[{"nombre": "jugo", "precio_unitario": 950, "cantidad": 1}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 1}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 1}], [{"nombre": "naranja", "precio_unitario": 350, "cantidad": 1}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 1}, {"nombre": "agua", "precio_unitario": 650, "cantidad": 10}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 3}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 1}, {"nombre": "manzana", "precio_unitario": 400, "cantidad": 13}, {"nombre": "agua", "precio_unitario": 650, "cantidad": 10}], [{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 7}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 5}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 7}], [{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 7}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 3}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 7}], [{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 7}, {"nombre": "sandia", "precio_unitario": 1500, "cantidad": 14}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 3}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 5}]]}]
    json9 = [{"numero_caja": 9, "compras": [[{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 2}, {"nombre": "manzana", "precio_unitario": 400, "cantidad": 13}], [{"nombre": "manzana", "precio_unitario": 400, "cantidad": 13}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 13}, {"nombre": "sandia", "precio_unitario": 1500, "cantidad": 13}], [{"nombre": "agua", "precio_unitario": 650, "cantidad": 9}, {"nombre": "jugo", "precio_unitario": 950, "cantidad": 10}], [{"nombre": "naranja", "precio_unitario": 350, "cantidad": 11}, {"nombre": "sandia", "precio_unitario": 1500, "cantidad": 13}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 13}], [{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 2}], [{"nombre": "cafe", "precio_unitario": 1350, "cantidad": 4}], [{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 2}, {"nombre": "galletas", "precio_unitario": 800, "cantidad": 13}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 4}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 13}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 11}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 2}]]}]
    json10 = [{"numero_caja": 10, "compras": [[{"nombre": "galletas", "precio_unitario": 800, "cantidad": 4}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 4}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 5}], [{"nombre": "naranja", "precio_unitario": 350, "cantidad": 4}, {"nombre": "cafe", "precio_unitario": 1350, "cantidad": 5}, {"nombre": "uvas", "precio_unitario": 1200, "cantidad": 5}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 4}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 4}, {"nombre": "manzana", "precio_unitario": 400, "cantidad": 6}], [{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 5}, {"nombre": "agua", "precio_unitario": 650, "cantidad": 7}, {"nombre": "naranja", "precio_unitario": 350, "cantidad": 4}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 1}], [{"nombre": "uvas", "precio_unitario": 1200, "cantidad": 5}, {"nombre": "sandia", "precio_unitario": 1500, "cantidad": 11}, {"nombre": "sandia", "precio_unitario": 1500, "cantidad": 11}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 1}], [{"nombre": "jugo", "precio_unitario": 950, "cantidad": 1}, {"nombre": "manzana", "precio_unitario": 400, "cantidad": 6}], [{"nombre": "galletas", "precio_unitario": 800, "cantidad": 4}]]}]

    jsonString = json1 + json2 + json3 + json4 + json5 + json6 + json7 + json8 + json9 + json10     
    print("jsonString",jsonString)
    dataframe =sc.parallelize(jsonString)
    testDF = readFiles(dataframe)   # Creción del Dataframe de Prueba
    SubtotalsDF = testDF.withColumn("SubTotal", \
                        testDF.cantidad * testDF.precio_unitario)

    Actual_Lista_Metricas = fn_metricas(SubtotalsDF)

    #El siguiente código funciona para calcular el percentile exacto
    #Tal y como lo detallo en el manual de la tarea
    total_por_caja_DF = fn_total_por_caja(SubtotalsDF)
    Rango_Percentil = total_por_caja_DF.select("numero_caja","Total_Dinero_Vendido",  
                    FN.percent_rank().over(Window.partitionBy()
                    .orderBy(total_por_caja_DF['Total_Dinero_Vendido'])).alias("Rango_Percentile"))
    Rango_Percentil.show()
    

    #Expected
    Expected_IDCajaVentaMax = 7
    Expected_IDCajaVentaMin = 10
    Expected_P25 = 98050.0
    Expected_P50 = 136100.0
    Expected_P75 = 141225.0
    Expected_IDArticuloMayorQTY = "galletas"
    Expected_IDArticuloMayorVenta = "cafe"

    Expected_Lista_Metricas = [Expected_IDCajaVentaMax,Expected_IDCajaVentaMin,\
                                Expected_P25,Expected_P50 ,Expected_P75 ,\
                                Expected_IDArticuloMayorQTY ,Expected_IDArticuloMayorVenta]

    assert Actual_Lista_Metricas  == Expected_Lista_Metricas
